services: 
  delivery-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: delivery
      POSTGRES_DB: delivery
    ports:
      - "5433:5432"
    volumes:
      - delivery-postgres-data:/var/lib/postgresql/data

  delivery-service:
    build:
      context: ./delivery-service
    environment:
      DELIVERY_DB_DSN: "host=delivery-postgres port=5432 user=delivery password=delivery dbname=delivery sslmode=disable"
    ports:
      - "8081:8080"
      - "9091:9090"
    depends_on:
      - delivery-postgres

  postgres: 
    image: postgres:latest 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: warehouse 
    ports: 
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  eventstore:
    image: eventstore/eventstore:latest 
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true 
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true 

    ports: 
      - "2113:2113"
      - "1113:1113"
      - "2112:2112"
    volumes: 
      - type: volume 
        source: eventstore-data 
        target: /var/lib/eventstore 
      - type: volume 
        source: eventstore-logs 
        target: /var/log/eventstore 

volumes: 
  delivery-postgres-data:
  eventstore-data: 
  eventstore-logs: 
